[project]
name = "gitx"
version = "1.0.3"
description = "给中国人用的 GitHub 加速下载与同步工具"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
{ name = "FLT18355", email = "cm18750724707a@outlook.com" }
]
requires-python = ">=3.14"
dependencies = [
    "prompt-toolkit>=3.0.43",
    "questionary>=2.1.1",
    "typer>=0.27.2",
]
[project.scripts]
gitx = "gitx:main"

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
